version: '3.4'

services: 
    go-api:
      container_name: go-htmx 
      build:
        context: ./
      ports:
        - 8080:8080
      environment:
        URL: localhost
        PORT: 8080
      links:
      - db
      depends_on:
      - db
    db:
      image: postgres
      container_name: postgres-go
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: usernamepg
        POSTGRES_DB: db
        POSTGRES_PASSWORD: password123
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U db" ]
        interval: 30s
        timeout: 30s
        retries: 3
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: