version: '3.4'

services: 
    go-api: 
      build:
        context: ./
      ports:
        - 8080:8080
      environment:
        URL: localhost
        PORT: 8080
      depends_on:
      - db
    db:
      image: postgres
      container_name: postgres-go
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: dev
        POSTGRES_DB: dev
        POSTGRES_PASSWORD: dev
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U dev" ]
        interval: 30s
        timeout: 30s
        retries: 3
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: